Arrays vs Lists

In [1]:
import numpy as np

In [2]:
lists = [1,2,3]
array = np.array([1,2,3])

In [3]:
lists

[1, 2, 3]

In [4]:
array

array([1, 2, 3])

# How do Lists and Arrays work?

In [5]:
for e in lists:
    print(e)

1
2
3


In [6]:
for e in array:
    print(e)

1
2
3


In [7]:
lists.append(4)
lists

[1, 2, 3, 4]

In [9]:
#There is no append function for an array, it is a fixed object
array.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [11]:
#Numpy focuses on Math, so adding 4 to the array physically addes four to each element in the array
#This is broadcasting where the value 4 is added to every element in the array
array + np.array([4])

array([5, 6, 7])

In [19]:
#Now we have three elements in the array, we wont be broadcasting but instead add to our existing array
#This only works when the arrays are of the same size, if not an error will be thrown
print(array)
print(array + np.array([4,10,20]))

[1 2 3]
[ 5 12 23]


In [18]:
#Similarly we can multiply the array by some value and it will apply the multiplication to each element
print(array)
print(2* array)

[1 2 3]
[2 4 6]
